-- ============================================================
-- MNMuslim.com — Supabase Database Schema
-- Run this in your Supabase SQL Editor to set up the database
-- ============================================================

-- 1. Create the listings table
create table if not exists listings (
  id          bigint generated by default as identity primary key,
  service_name   text not null,
  provider_name  text not null,
  category       text not null,
  description    text not null,
  service_area   text not null,
  phone          text,
  email          text not null,
  website        text,
  instagram      text,
  approved       boolean not null default false,
  created_at     timestamptz not null default now()
);

-- 2. Enable Row Level Security
alter table listings enable row level security;

-- 3. Allow anyone to READ approved listings (public directory)
create policy "Public can read approved listings"
  on listings for select
  using (approved = true);

-- 4. Allow anyone to INSERT (submit a listing — always starts as unapproved)
create policy "Anyone can submit a listing"
  on listings for insert
  with check (approved = false);

-- 5. Seed some initial approved listings so the site isn't empty on launch
insert into listings (service_name, provider_name, category, description, service_area, phone, email, website, instagram, approved)
values
  ('Private Math & Science Tutoring', 'Omar Abdi', 'edu',
   'Experienced math and science tutor for grades 6–12 and college prep. Specializing in algebra, calculus, biology, and ACT/SAT prep. Flexible scheduling, in-person or online.',
   'Twin Cities Metro', '(651) 555-0142', 'omar.abdi.tutors@example.com', '', '@omarabditutor', true),

  ('Web Design & Development', 'Yusuf Ali', 'tech',
   'Full-stack web developer with 8+ years of experience. I build fast, modern websites and web apps for small businesses and nonprofits. Reasonable rates for community members.',
   'Statewide (Remote)', '(612) 555-0198', 'yusuf@example.com', 'https://example.com', '@codebyali', true),

  ('Halal Wedding Photography', 'Hodan Warsame', 'photo',
   'Professional wedding and event photographer. I understand the needs of Muslim families and ensure your coverage is respectful, beautiful, and captures your day perfectly.',
   'Minnesota & Midwest', '(763) 555-0217', 'hodan@example.com', 'https://example.com', '@hodanphoto', true),

  ('Tax Preparation & Bookkeeping', 'Ibrahim Noor', 'fin',
   'CPA with 12 years experience. Specializing in small business taxes, personal returns, and bookkeeping. Understands halal finance considerations.',
   'Twin Cities', '(952) 555-0083', 'ibrahim@example.com', 'https://example.com', '', true),

  ('Immigration Law Services', 'Safia Ahmed, Esq.', 'legal',
   'Licensed immigration attorney helping families with green cards, citizenship, family petitions, asylum, and DACA renewals. Free initial consultation for community members.',
   'Minneapolis', '(612) 555-0321', 'safia@example.com', 'https://example.com', '@ahmedlawmn', true),

  ('Life & Career Coaching', 'Amina Hassan', 'biz',
   'Certified life coach helping Muslim professionals navigate career transitions, leadership development, and work-life balance grounded in Islamic values.',
   'Statewide (Remote & In-Person)', '', 'amina@example.com', 'https://example.com', '@aminacoachesmn', true),

  ('Home Cleaning Services', 'Muna Ibrahim', 'home',
   'Reliable, thorough home cleaning. Weekly, biweekly, or one-time deep clean options. Trusted by dozens of families in the metro area for over 5 years.',
   'Minneapolis & St. Paul', '(651) 555-0167', 'munacleans@example.com', '', '', true),

  ('Personal Training & Fitness', 'Khalid Hassan', 'fitness',
   'NASM-certified personal trainer. Specialized programs for Muslim clients with respect for modest workout environments and fasting schedules. Online and in-person.',
   'Burnsville, MN', '(952) 555-0245', 'khalid@example.com', '', '@fitbykhalid', true),

  ('Somali–English Translation & Interpretation', 'Faadumo Osman', 'other',
   'Professional interpreter and translator for medical, legal, and government settings. Available for in-person and phone interpretation. 10+ years experience.',
   'Twin Cities Metro', '(612) 555-0399', 'faadumo@example.com', '', '', true),

  ('Event Decoration & Styling', 'Leyla Abshir', 'events',
   'Full event decoration for weddings, Eid celebrations, graduations, and corporate events. Custom floral, balloon, and backdrop styling that fits any budget.',
   'Minneapolis, MN', '(763) 555-0088', 'leyla@example.com', 'https://example.com', '@leylaeventsco', true),

  ('Childcare & Babysitting', 'Nimo Jama', 'child',
   'Experienced childcare provider and certified nanny. Available for part-time, full-time, or evening care. Experienced with Muslim dietary needs and prayer times.',
   'St. Paul, MN', '(651) 555-0454', 'nimo@example.com', '', '', true),

  ('AI & Tech Consulting', 'Abdirahman Farah', 'tech',
   'Helping small businesses and nonprofits leverage AI tools to save time and grow. Workshops, 1-on-1 consulting, and implementation support for Muslim-owned businesses.',
   'Statewide (Remote)', '(612) 555-0512', 'abdi@example.com', 'https://example.com', '@techbyfarah', true);

-- ============================================================
-- ADMIN: To approve a pending listing, run:
-- update listings set approved = true where id = <listing_id>;
--
-- To view all pending listings:
-- select id, service_name, provider_name, email, created_at
-- from listings where approved = false order by created_at;
-- ============================================================
